// MongoDB 대신 사용할 Mock 데이터 생성
export const mockUsers = [
  {
    _id: "1",
    email: "minji.mom@example.com",
    nickname: "민지맘",
    avatar: "/placeholder.svg?height=40&width=40",
    location: "서울 강남구",
    interests: ["신생아케어", "유아놀이", "홈스쿨링"],
    verified: true,
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2023-03-15"),
  },
  {
    _id: "2",
    email: "seojun.mom@example.com",
    nickname: "서준이엄마",
    avatar: "/placeholder.svg?height=40&width=40",
    location: "서울 서초구",
    interests: ["편식해결", "유아식", "놀이활동"],
    verified: true,
    createdAt: new Date("2023-04-20"),
    updatedAt: new Date("2023-04-20"),
  },
  {
    _id: "3",
    email: "yejun.mom@example.com",
    nickname: "예준맘",
    avatar: "/placeholder.svg?height=40&width=40",
    location: "서울 송파구",
    interests: ["초등교육", "한글교육", "수학교육"],
    verified: true,
    createdAt: new Date("2023-05-10"),
    updatedAt: new Date("2023-05-10"),
  },
  {
    _id: "4",
    email: "working.mom@example.com",
    nickname: "워킹맘수진",
    avatar: "/placeholder.svg?height=40&width=40",
    location: "서울 마포구",
    interests: ["워킹맘", "시간관리", "육아용품"],
    verified: false,
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2023-06-01"),
  },
]

export const mockPosts = [
  {
    _id: "1",
    authorId: "1",
    content:
      "오늘 아이와 함께 만든 색깔 놀이예요! 물감 대신 식용 색소를 사용해서 안전하게 놀 수 있어요. 2세 아이도 정말 좋아하네요 ✨",
    images: ["/placeholder.svg?height=200&width=200"],
    category: "play" as const,
    ageGroup: "0-2" as const,
    tags: ["색깔놀이", "안전놀이", "집콕놀이"],
    likes: ["2", "3"],
    bookmarks: ["2"],
    commentCount: 5,
    createdAt: new Date("2024-01-15T10:30:00"),
    updatedAt: new Date("2024-01-15T10:30:00"),
    author: mockUsers[0],
  },
  {
    _id: "2",
    authorId: "2",
    content:
      "아이가 편식이 심해서 고민이었는데, 이렇게 예쁘게 플레이팅하니까 잘 먹네요! 브로콜리도 나무라고 하면서 먹어요 😊",
    images: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
    category: "food" as const,
    ageGroup: "3-5" as const,
    tags: ["편식", "플레이팅", "유아식"],
    likes: ["1", "3", "4"],
    bookmarks: ["1", "3"],
    commentCount: 8,
    createdAt: new Date("2024-01-15T09:15:00"),
    updatedAt: new Date("2024-01-15T09:15:00"),
    author: mockUsers[1],
  },
  {
    _id: "3",
    authorId: "3",
    content:
      "초등학교 입학 준비 어떻게 하고 계신가요? 한글은 어느 정도까지 가르쳐야 할지 궁금해요. 경험담 공유해주세요!",
    images: [],
    category: "education" as const,
    ageGroup: "6-8" as const,
    tags: ["초등입학", "한글교육", "입학준비"],
    likes: ["1", "2"],
    bookmarks: ["1"],
    commentCount: 12,
    createdAt: new Date("2024-01-15T08:45:00"),
    updatedAt: new Date("2024-01-15T08:45:00"),
    author: mockUsers[2],
  },
  {
    _id: "4",
    authorId: "4",
    content:
      "워킹맘들 어떻게 시간 관리하시나요? 아침에 아이 준비시키고 출근하는게 너무 힘들어요 😭 꿀팁 있으면 공유해주세요!",
    images: [],
    category: "advice" as const,
    ageGroup: "all" as const,
    tags: ["워킹맘", "시간관리", "육아고민"],
    likes: ["1", "2", "3"],
    bookmarks: ["2", "3"],
    commentCount: 15,
    createdAt: new Date("2024-01-14T20:30:00"),
    updatedAt: new Date("2024-01-14T20:30:00"),
    author: mockUsers[3],
  },
  {
    _id: "5",
    authorId: "1",
    content:
      "아이 감기 걸렸을 때 집에서 할 수 있는 관리법 공유해요. 가습기 틀어주고 따뜻한 물 많이 먹이는게 도움이 되더라구요.",
    images: [],
    category: "health" as const,
    ageGroup: "0-2" as const,
    tags: ["감기관리", "건강관리", "홈케어"],
    likes: ["2", "4"],
    bookmarks: ["2", "3", "4"],
    commentCount: 7,
    createdAt: new Date("2024-01-14T15:20:00"),
    updatedAt: new Date("2024-01-14T15:20:00"),
    author: mockUsers[0],
  },
  {
    _id: "6",
    authorId: "2",
    content:
      "유아 독서 습관 만들기! 매일 밤 책 읽어주기 시작한지 한 달째인데 아이가 스스로 책을 찾아서 읽으려고 해요 📚",
    images: ["/placeholder.svg?height=200&width=200"],
    category: "education" as const,
    ageGroup: "3-5" as const,
    tags: ["독서습관", "책읽기", "교육"],
    likes: ["1", "3"],
    bookmarks: ["1"],
    commentCount: 6,
    createdAt: new Date("2024-01-13T19:45:00"),
    updatedAt: new Date("2024-01-13T19:45:00"),
    author: mockUsers[1],
  },
]

export const mockComments = [
  {
    _id: "1",
    postId: "1",
    authorId: "2",
    content: "우와 정말 좋은 아이디어네요! 저도 해봐야겠어요",
    likes: ["1"],
    createdAt: new Date("2024-01-15T11:00:00"),
    author: mockUsers[1],
  },
  {
    _id: "2",
    postId: "1",
    authorId: "3",
    content: "식용 색소는 어디서 구매하셨나요?",
    likes: [],
    createdAt: new Date("2024-01-15T11:15:00"),
    author: mockUsers[2],
  },
  {
    _id: "3",
    postId: "2",
    authorId: "1",
    content: "플레이팅 너무 예뻐요! 저희 아이도 편식이 심한데 따라해볼게요",
    likes: ["2"],
    createdAt: new Date("2024-01-15T09:30:00"),
    author: mockUsers[0],
  },
]

export const mockChildren = [
  {
    _id: "1",
    parentId: "1",
    name: "민지",
    age: 2,
    gender: "female" as const,
    createdAt: new Date("2023-03-15"),
  },
  {
    _id: "2",
    parentId: "2",
    name: "서준",
    age: 4,
    gender: "male" as const,
    createdAt: new Date("2023-04-20"),
  },
  {
    _id: "3",
    parentId: "2",
    name: "서윤",
    age: 2,
    gender: "female" as const,
    createdAt: new Date("2023-04-20"),
  },
  {
    _id: "4",
    parentId: "3",
    name: "예준",
    age: 7,
    gender: "male" as const,
    createdAt: new Date("2023-05-10"),
  },
]
